Workig with Numpy

In [3]:
import numpy as np

In [4]:
np.array([1,8,5,4,3,2])

array([1, 8, 5, 4, 3, 2])

In [5]:
b = np.array([[2,3,7],[4,7,8]])

In [6]:
b

array([[2, 3, 7],
       [4, 7, 8]])

In [7]:
#showing the shape of array created
b.shape

(2, 3)

In [8]:
b.dtype


dtype('int64')

In [9]:
#showing the dimation of array
b.ndim

2

In [10]:
# using range with numpy
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

 why use numpy 

In [21]:
c = range(10000)
d = [i**2 for i in range(10000)]

In [23]:
%timeit list(map(lambda x,y: x*y, c, d))

968 µs ± 10.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [24]:
c1 = np.array(c)
c2 = np.array(d)

In [25]:
%timeit c1*c2

5.47 µs ± 345 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [26]:
 np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [28]:
#creating identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
#matrix with 2x2
np.full((3,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [30]:
#fill the diagonal values
np.diag([1,2,3,4,5,6])

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [33]:
#stacking the elements
v = np.array([3,2,4])
v

array([3, 2, 4])

In [34]:
np.tile(v,(2,4))

array([[3, 2, 4, 3, 2, 4, 3, 2, 4, 3, 2, 4],
       [3, 2, 4, 3, 2, 4, 3, 2, 4, 3, 2, 4]])

In [35]:
#using random function in numpy
np.random.random()

0.019651807260390286

In [37]:
np.random.random((3,3))

array([[0.7004051 , 0.80259076, 0.47282612],
       [0.44075594, 0.03521769, 0.63614491],
       [0.97562299, 0.91884205, 0.1176217 ]])

In [38]:
# creating an equal distributed values
a = np.linspace(1,50,60)

In [39]:
a

array([ 1.        ,  1.83050847,  2.66101695,  3.49152542,  4.3220339 ,
        5.15254237,  5.98305085,  6.81355932,  7.6440678 ,  8.47457627,
        9.30508475, 10.13559322, 10.96610169, 11.79661017, 12.62711864,
       13.45762712, 14.28813559, 15.11864407, 15.94915254, 16.77966102,
       17.61016949, 18.44067797, 19.27118644, 20.10169492, 20.93220339,
       21.76271186, 22.59322034, 23.42372881, 24.25423729, 25.08474576,
       25.91525424, 26.74576271, 27.57627119, 28.40677966, 29.23728814,
       30.06779661, 30.89830508, 31.72881356, 32.55932203, 33.38983051,
       34.22033898, 35.05084746, 35.88135593, 36.71186441, 37.54237288,
       38.37288136, 39.20338983, 40.03389831, 40.86440678, 41.69491525,
       42.52542373, 43.3559322 , 44.18644068, 45.01694915, 45.84745763,
       46.6779661 , 47.50847458, 48.33898305, 49.16949153, 50.        ])

In [57]:
d = np.arange(24).reshape(2,3,-1)

In [58]:
d.shape

(2, 3, 4)

In [60]:
#Accessing an element from array in numpy
a = np.array([2,5,4,6,88,90,35,343,34])

In [61]:
a[1]

5

In [63]:
a[5:]

array([ 90,  35, 343,  34])

In [64]:
a[0:6]

array([ 2,  5,  4,  6, 88, 90])

In [65]:
#2D elements a
b = np.array([[2,3,4],[7,8,9],[7,4,1]])

In [66]:
b

array([[2, 3, 4],
       [7, 8, 9],
       [7, 4, 1]])

In [69]:
#accessing the value 4
b[0,2]

4

In [70]:
b>5

array([[False, False, False],
       [ True,  True,  True],
       [ True, False, False]])

In [71]:
b<10

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [72]:
# dealing with subset in numpy
c = np.arange(10)

In [73]:
d = c

In [74]:
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
d[0]= 10

In [79]:
d


array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [80]:
c

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [84]:
# sharing the same memory
np.shares_memory(c,d)

True

In [89]:
a = np.arange(10)

In [90]:
#making a copy of elements
b = a.copy()

In [91]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
#changing the value of element in array
b[0] = 16

In [93]:
b

array([16,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [95]:
d = np.array([[3,4,5],[7,8,9]])

In [96]:
#Transposing the values in array
d.T

array([[3, 7],
       [4, 8],
       [5, 9]])

In [97]:
e = np.array([[4,6,3],[7,20,5]])

In [98]:
#doing booline operations
e==d

array([[False, False, False],
       [ True, False, False]])

In [100]:
#Doing stack operations horizontal
np.hstack((d,e))

array([[ 3,  4,  5,  4,  6,  3],
       [ 7,  8,  9,  7, 20,  5]])

In [101]:
#vertical stack
np.vstack((d,e))

array([[ 3,  4,  5],
       [ 7,  8,  9],
       [ 4,  6,  3],
       [ 7, 20,  5]])

In [102]:
# Math operations in numpy
a = np.arange(20)

In [103]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [105]:
#getting all the sin value in array
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721])

In [106]:
#getting the sum of all the element in array
np.sum(a)

190

In [108]:
#getting the median
np.median(a)

9.5

In [109]:
#getting the mean
np.mean(a)

9.5

In [110]:
#stand
np.std(a)

5.766281297335398

In [111]:
b = np.arange(1,10).reshape(3,3)

In [112]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [114]:
#getting detemine for a matrix
np.linalg.det(b)

-9.51619735392994e-16

In [115]:
# inverse
np.linalg.inv(b)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [116]:
c = b.T

In [117]:
c

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [118]:
#dot product
np.dot(d,c)

array([[ 26,  62,  98],
       [ 50, 122, 194]])

In [119]:
#Boolian operations
a = np.array([2,2,0], dtype=bool)
b = np.array([2,0,2], dtype=bool)

In [120]:
np.logical_or(a,b)

array([ True,  True,  True])

In [121]:
np.logical_not(a,b)

array([False, False,  True])