In [1]:
import numpy as np

In [2]:
a= np.array([3,4,6])

In [3]:
b = np.array([7,8,9])

In [4]:
print(np.dot(a,b))

107


In [6]:
#creating the matrix
x = np.matrix([[1,2,3,4],[5,6,7,8],[2,3,4,5],[6,7,8,9]])

In [7]:
x

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8],
        [2, 3, 4, 5],
        [6, 7, 8, 9]])

In [8]:
x.shape

(4, 4)

In [9]:
 a = np.matrix([[1,4,5],[3,5,7],[5,7,8]])

In [10]:
a

matrix([[1, 4, 5],
        [3, 5, 7],
        [5, 7, 8]])

In [11]:
b = np.matrix([[2],[4],[6]])

In [12]:
b

matrix([[2],
        [4],
        [6]])

In [13]:
print(a*b)

[[48]
 [68]
 [86]]


In [14]:
print(a+b)

[[ 3  6  7]
 [ 7  9 11]
 [11 13 14]]


In [15]:
from numpy import linalg as LA

In [16]:
#ranking of matrix
x = np.matrix([[2,3,4],[5,6,7],[9,8,7]])

In [17]:
x

matrix([[2, 3, 4],
        [5, 6, 7],
        [9, 8, 7]])

In [18]:
x.shape

(3, 3)

In [19]:
LA.matrix_rank(a)

3