In [1]:
#importing the numpy module
import numpy as np

In [2]:
#crating array
a = np.array([23,45,35,53,555])
b = np.array([554,35,56,66,66])

In [4]:
#Accessing the elements in array use of index
print(a[3],b[4])

53 66


In [6]:
#Creating a multi-dimension array
a = np.array([[35,3,36,67],[55,44,994,64]])
print(a)

[[ 35   3  36  67]
 [ 55  44 994  64]]


In [8]:
#Accessing elements from multi-dimension array use of index
print(a[1][3])

64


In [11]:
#unsing numpy function to build array "Full function"
a = np.full((3,5,4),78)
print(a)

[[[78 78 78 78]
  [78 78 78 78]
  [78 78 78 78]
  [78 78 78 78]
  [78 78 78 78]]

 [[78 78 78 78]
  [78 78 78 78]
  [78 78 78 78]
  [78 78 78 78]
  [78 78 78 78]]

 [[78 78 78 78]
  [78 78 78 78]
  [78 78 78 78]
  [78 78 78 78]
  [78 78 78 78]]]


In [14]:
#using Empty function
a = np.empty((4,4))
print(a)
#Random function
b = np.random.random((3,3))
print(b)


[[4.67708712e-310 0.00000000e+000 6.92889958e-310 6.92889958e-310]
 [6.92889981e-310 6.92889958e-310 6.92889958e-310 6.92889958e-310]
 [6.92889958e-310 6.92889958e-310 6.92889958e-310 6.92889958e-310]
 [6.92889958e-310 6.92889958e-310 6.92889958e-310 6.92889958e-310]]
[[0.98641313 0.65388669 0.84856169]
 [0.5151278  0.761959   0.55234104]
 [0.06695553 0.84735184 0.45549674]]


In [16]:
#Using the range function
a = np.arange(10,40,5)
print(a)

[10 15 20 25 30 35]


In [20]:
#using linespase creating avalues that are equaly spaced
a = np.linspace(0,1000,101)
print(a)
print(a.size)

[   0.   10.   20.   30.   40.   50.   60.   70.   80.   90.  100.  110.
  120.  130.  140.  150.  160.  170.  180.  190.  200.  210.  220.  230.
  240.  250.  260.  270.  280.  290.  300.  310.  320.  330.  340.  350.
  360.  370.  380.  390.  400.  410.  420.  430.  440.  450.  460.  470.
  480.  490.  500.  510.  520.  530.  540.  550.  560.  570.  580.  590.
  600.  610.  620.  630.  640.  650.  660.  670.  680.  690.  700.  710.
  720.  730.  740.  750.  760.  770.  780.  790.  800.  810.  820.  830.
  840.  850.  860.  870.  880.  890.  900.  910.  920.  930.  940.  950.
  960.  970.  980.  990. 1000.]
101


In [21]:
#Arithmetic operations 
a = np.array([[2,4,5,6],[4,6,7,8]])

#addition
print(a + 5)

#substraction
print(a - 5)

#multiplication
print(a * 5)

#division
print(a / 5)

[[ 7  9 10 11]
 [ 9 11 12 13]]
[[-3 -1  0  1]
 [-1  1  2  3]]
[[10 20 25 30]
 [20 30 35 40]]
[[0.4 0.8 1.  1.2]
 [0.8 1.2 1.4 1.6]]


In [23]:
#Combination of array "Concatenate, stack,hstack,vstack"
a = np.array([5,6,8,9])
b = np.array([7,8,9,3])

print(np.concatenate((a,b)))

print(np.stack((a,b)))



[5 6 8 9 7 8 9 3]
[[5 6 8 9]
 [7 8 9 3]]


In [27]:
#Splitting fuctions "split, hsplit, vsplit"
a = np.array([[10,20,30],[40,50,60],[70,80,90],[100,110,120]])

print(np.split(a,2))

print(np.split(a,4))

[array([[10, 20, 30],
       [40, 50, 60]]), array([[ 70,  80,  90],
       [100, 110, 120]])]
[array([[10, 20, 30]]), array([[40, 50, 60]]), array([[70, 80, 90]]), array([[100, 110, 120]])]


In [28]:
#Laoding and Saving
a = np.array([[10,20,30],[40,50,60],[70,80,90]])

np.save("myarray.npy", a)

a = np.load("myarray.npy")
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [30]:
#creating a CSV file
a = np.array([[10,20,30],[40,50,60],[70,80,90],[100,110,120]])

np.savetxt("myarray.csv", a)
print(a)

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]


In [34]:
a = np.loadtxt("myarray.csv", delimiter=";")
print(a)

ValueError: could not convert string to float: '1.000000000000000000e+01 2.000000000000000000e+01 3.000000000000000000e+01'